name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build typescript project
        run: |
          npm install
          npm run build

      - name: Run ESLint and Prettier
        run: |
          npm run lint
          npm run prettier

      - name: Run integration tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build:example
          start: npm run cypress:prepare
